# Generated by Django 2.2.5 on 2019-09-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='counter_name',
            field=models.CharField(default='v00', max_length=200),
        ),
    ]
