# Generated by Django 2.2.5 on 2019-09-29 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_counter_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='counter_name',
        ),
    ]
